name: Deploy to Voices Ignited Website

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files to deploy
        run: |
          echo "Files to be deployed:"
          ls -la

      - name: Deploy to Voices Ignited
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: "162.0.232.112"
          username: Tech@voicesignited.org
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          port: 21
          protocol: ftp
          log-level: verbose
          server-dir: /
          local-dir: ./
          state-name: .ftp-deploy-sync-state.json
          dry-run: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env*
            **/.github/**
            **/test/**
            deploy.sh
            server-setup.sh
            **/*.log
            **/*.md
            **/docs/**
            .DS_Store
            Thumbs.db

      - name: Verify deployment
        if: success()
        run: |
          echo "Deployment completed. Please verify at http://162.0.232.112"
          echo "Timestamp: $(date)"

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Website deployed successfully"
          else
            echo "Deployment failed"
            exit 1
          fi
