name: Deploy to Voices Ignited Website

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Voices Ignited
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.voicesignited.org
          username: Tech@voicesignited.org
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          port: 21
          protocol: ftps
          server-dir: public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env*
            **/.github/**
            **/test/**
            deploy.sh
            server-setup.sh
            **/*.log
            **/*.md
            **/docs/**

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "Website deployed successfully to voicesignited.org"
          else
            echo "Deployment failed"
            exit 1
          fi
